#!/usr/bin/env python3
"""Register a release on this blog.

The blog repo holds no binaries: the zip is published as a **GitHub Release
asset**, and this script records what the pages need to link it -- version,
asset name, tag, size, sha256. URL shape is derived at render time from
SITE.repo in assets/config.js, so the repo name lives in exactly one place.

    # publish the artifact (one time per version):
    #   web UI : repo -> Releases -> Draft a new release -> tag v1.0 -> attach the zip
    #   gh CLI : gh release create v1.0 path/to/tf2-aimbot-v1.0.zip
    # then tell the blog about it:
    python scripts/add_release.py --id tf2-aimbot \\
        --zip ../tf2-aimbot/dist/tf2-aimbot-v1.0.zip \\
        --version v1.0 --date 2026-09-21 \\
        --name "Titanfall 2 战役辅助" --game "Titanfall 2" --scope "仅单人战役" \\
        --game-version v2.0.11.0 --guide posts/tf2-aimbot.html#usage \\
        --summary "..." --note "..." --label "单人战役"

On an update only --zip/--version/--date are needed; everything else is
inherited from the existing entry unless passed again.

    python scripts/add_release.py --list
    python scripts/add_release.py --id tf2-aimbot --remove
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOWNLOADS_JS = ROOT / "assets" / "downloads.js"
CONFIG_JS = ROOT / "assets" / "config.js"
PREFIX = "// Generated by scripts/add_release.py -- do not hand-edit.\nconst DOWNLOADS = "
FIELDS = [
    "id", "name", "game", "scope", "version", "date", "gameVersion",
    "guide", "summary", "tags", "tag", "asset", "size", "sha256",
]


def read_entries() -> list[dict]:
    if not DOWNLOADS_JS.exists():
        return []
    text = DOWNLOADS_JS.read_text(encoding="utf-8")
    if PREFIX not in text:
        sys.exit(f"{DOWNLOADS_JS} is not in the generated format; refusing to touch it")
    return json.loads(text.split(PREFIX, 1)[1].rstrip().rstrip(";"))


def write_entries(entries: list[dict]) -> None:
    entries = sorted(entries, key=lambda e: (e["date"], e["id"]), reverse=True)
    ordered = [{k: e[k] for k in FIELDS if k in e} for e in entries]
    DOWNLOADS_JS.write_text(
        PREFIX + json.dumps(ordered, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )


def repo_from_config() -> str:
    m = re.search(r'repo\s*:\s*"([^"]*)"', CONFIG_JS.read_text(encoding="utf-8"))
    return m.group(1).strip() if m else ""


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser(description="add/update a blog release")
    ap.add_argument("--id", help="stable slug, e.g. tf2-aimbot")
    ap.add_argument("--zip", help="local artifact to publish (used for size/sha256/asset name)")
    ap.add_argument("--version", help="e.g. v1.0")
    ap.add_argument("--date", help="release date, YYYY-MM-DD")
    ap.add_argument("--tag", help="release tag in GitHub (default: same as --version)")
    ap.add_argument("--asset", help="asset file name in the release (default: zip basename)")
    ap.add_argument("--repo", help='override "owner/repo" from assets/config.js (not stored)')
    ap.add_argument("--name", help="display name")
    ap.add_argument("--game", help="target game")
    ap.add_argument("--scope", help='e.g. "仅单人战役"')
    ap.add_argument("--game-version", dest="gameVersion", help="required game build")
    ap.add_argument("--guide", help="relative link to the usage post (may carry #anchor)")
    ap.add_argument("--summary", help="one-line description")
    ap.add_argument("--note", action="append", dest="notes",
                    help="requirement/warning line (repeatable)")
    ap.add_argument("--label", action="append", dest="labels",
                    help="short label shown on the card, e.g. 单人战役 (repeatable)")
    ap.add_argument("--list", action="store_true", help="print current entries and exit")
    ap.add_argument("--remove", action="store_true", help="drop the entry")
    args = ap.parse_args()

    entries = read_entries()
    repo = args.repo or repo_from_config()

    if args.list:
        for e in entries:
            url = (f"https://github.com/{repo}/releases/download/{e['tag']}/{e['asset']}"
                   if repo else "(SITE.repo 未配置)")
            print(f"{e['id']:<14} {e['version']:<9} {e['date']}  {e['asset']}  "
                  f"{e['size']} bytes  sha256={e['sha256'][:16]}...\n"
                  f"{'':<14} {url}")
        if not repo:
            print("\n提示:把 assets/config.js 里的 SITE.repo 填成 你的用户名/仓库名 后,"
                  "页面上的下载才会生效。")
        return 0

    if not args.id:
        ap.error("--id is required")

    old = next((e for e in entries if e["id"] == args.id), None)

    if args.remove:
        if not old:
            print(f"no entry with id {args.id}")
            return 0
        entries.remove(old)
        write_entries(entries)
        print(f"removed {args.id} from the blog "
              f"(the GitHub release itself is untouched -- delete it in the repo UI if you want)")
        return 0

    # --note/--label collect into notes/tags; everything else maps straight over.
    provided = {k: v for k, v in vars(args).items()
                if k not in ("list", "remove", "zip", "id", "repo", "labels")
                and v is not None}
    if args.labels:
        provided["tags"] = args.labels

    merged = dict(old or {})
    merged.update(provided)
    merged["id"] = args.id

    if not args.zip:
        sys.exit("--zip is required (the artifact you already uploaded to a release)")
    src = Path(args.zip).expanduser()
    if not src.is_file():
        sys.exit(f"zip not found: {src}")
    for field in ("name", "game", "version", "date"):
        if not merged.get(field):
            sys.exit(f"--{field.replace('_', '-')} is required for a new entry")

    merged.setdefault("tag", merged["version"])
    merged.setdefault("asset", src.name)
    merged.update(size=src.stat().st_size, sha256=sha256_of(src))

    if re.search(r"[^A-Za-z0-9._-]", merged["asset"]):
        print(f"warning: asset name {merged['asset']!r} needs URL encoding when fetched; "
              f"rename it to use only letters/digits/._- if you can")

    entries = [e for e in entries if e["id"] != args.id] + [merged]
    write_entries(entries)

    print(f"\n{merged['name']} {merged['version']}  ({merged['game']})")
    print(f"  asset   {merged['asset']}  {merged['size']} bytes")
    print(f"  sha256  {merged['sha256']}")
    print(f"  tag     {merged['tag']}")
    if repo:
        print(f"  link    https://github.com/{repo}/releases/download/"
              f"{merged['tag']}/{merged['asset']}")
    else:
        print("  link    (先填 assets/config.js 的 SITE.repo,页面上的下载才会生效)")
    print("\n如果这个版本还没发 Release:")
    print(f"  gh release create {merged['tag']} \"{src}\"   "
          f"# 或用网页:仓库 → Releases → Draft a new release,"
          f"附件名必须是 {merged['asset']}")
    print(f"\nnext: git add -A && git commit -m \"release: {merged['id']} {merged['version']}\"")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
